# Generated by Django 3.1.1 on 2020-10-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='p_facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='p_instragram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='p_line',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='p_phone',
        ),
        migrations.RemoveField(
            model_name='thammart',
            name='t_count',
        ),
    ]
