# Generated by Django 3.1.1 on 2020-10-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201017_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p_facebook',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='p_instragram',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='p_line',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='p_phone',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thammart',
            name='t_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
