# Generated by Django 3.1.1 on 2020-10-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201017_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='thammart',
            name='t_price',
            field=models.CharField(default='200', max_length=10),
            preserve_default=False,
        ),
    ]
