# Generated by Django 3.1.1 on 2020-10-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201023_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thammart',
            name='t_image',
            field=models.BinaryField(blank=True),
        ),
    ]
