# Generated by Django 3.1.1 on 2020-10-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201023_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thammart',
            name='t_image',
            field=models.CharField(max_length=1000),
        ),
    ]
