# Generated by Django 3.1.1 on 2020-10-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201024_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_facebook',
            field=models.CharField(default='0000000', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_instragram',
            field=models.CharField(default='0000000', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_line',
            field=models.CharField(default='0000000', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_mail',
            field=models.CharField(default='0000000', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_phone',
            field=models.CharField(default='0000000', max_length=40),
        ),
    ]
