# Generated by Django 3.1.1 on 2020-11-01 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201101_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='thammart',
            name='t_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
