# Generated by Django 3.1.1 on 2020-11-01 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_thammart_t_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thammart',
            name='t_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
