# Generated by Django 3.1.1 on 2020-11-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201101_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='p_facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='p_instragram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='p_line',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='p_phone',
        ),
        migrations.AddField(
            model_name='thammart',
            name='t_channel',
            field=models.CharField(default='0000000000000000', max_length=1000),
        ),
    ]
