# Generated by Django 3.1.1 on 2020-11-01 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_auto_20201025_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='p_mymart',
        ),
        migrations.AlterField(
            model_name='thammart',
            name='t_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
